#- name: Install Nginx
#  ansible.builtin.yum:
#    name: nginx
#    state: latest


#- name: Start Nginx
#  ansible.builtin.systemd_service:
#    name: nginx
#    state: started
#    enabled: yes


-  name: print variable
   ansible.builtin.debug:
     msg: URL = {{ URL }}

-  name: print variable task variable defined
   ansible.builtin.debug:
     msg:  URL = {{ URL }}
   vars:
     URL: tasks.google.com